services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: scrapDB             # match the DB name your app uses
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "mongo", "--password", "123456", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    container_name: scrap-app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:123456@mongo:27017/scrapDB?authSource=admin

volumes:
  mongo_data:

